// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD8yeeS-0z6OGwR1GsZfY4u1Vu9tKYBsQ',
    appId: '1:770602198487:web:0daf7d8d5f9b5f8d095792',
    messagingSenderId: '770602198487',
    projectId: 'carefull-b40bc',
    authDomain: 'carefull-b40bc.firebaseapp.com',
    storageBucket: 'carefull-b40bc.firebasestorage.app',
    measurementId: 'G-5GQW2RXS9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRXR0m9NIYGlbyrKDOn0mYd_C3uRjVtk',
    appId: '1:770602198487:android:5688853f616294e4095792',
    messagingSenderId: '770602198487',
    projectId: 'carefull-b40bc',
    storageBucket: 'carefull-b40bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ivCxbD9dfbqkylpjplMC2ZEjLHjMmR0',
    appId: '1:770602198487:ios:753c728aa6aa96a8095792',
    messagingSenderId: '770602198487',
    projectId: 'carefull-b40bc',
    storageBucket: 'carefull-b40bc.firebasestorage.app',
    iosBundleId: 'com.example.carefull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ivCxbD9dfbqkylpjplMC2ZEjLHjMmR0',
    appId: '1:770602198487:ios:753c728aa6aa96a8095792',
    messagingSenderId: '770602198487',
    projectId: 'carefull-b40bc',
    storageBucket: 'carefull-b40bc.firebasestorage.app',
    iosBundleId: 'com.example.carefull',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD8yeeS-0z6OGwR1GsZfY4u1Vu9tKYBsQ',
    appId: '1:770602198487:web:9b60e5015bea3845095792',
    messagingSenderId: '770602198487',
    projectId: 'carefull-b40bc',
    authDomain: 'carefull-b40bc.firebaseapp.com',
    storageBucket: 'carefull-b40bc.firebasestorage.app',
    measurementId: 'G-J4JV8PQHV1',
  );
}
